### ISSUE TITLE
1.20.1?

### ISSUE THREAD

**Issue by wolfieboy09** [lightning2401/northstar#16]
Could really use in my modpack :D

**Comment by Rockiecraft** [comment]
on the curseforge page 
![image](https://github.com/user-attachments/assets/c1b55812-59da-4c35-a79b-895f3c298a62)

**Comment by DadamaldaDad** [comment]
I'm really hyped. I don't like pressuring developers, so stay happy and healthy. Good luck working on the mod. Appreciate what you've done, this mod is much more polished than Creating Space.

**Comment by lightning2401** [comment]
mod has been updated to 1.20.1
