### ISSUE TITLE
нету порта на версию 1.20.1 по какой причине?

### ISSUE THREAD

**Issue by timurmatveeveduardovich** [lightning2401/northstar#32]
многие люди играют на ней и очень обидно когда понравившийся мод не подходит

**Comment by timurmatveeveduardovich** [comment]
if you don't know Russian, I'm duplicating it into English why there is no mod for 1.20.1, many people play on this version and it's a shame to see that the mod they like is not available

**Comment by lightning2401** [comment]
Mod has since been ported to 1.20.1
