### ISSUE TITLE
Don't know how, don't ask why, pls fast

### ISSUE THREAD

**Issue by davethemodderguy** [lightning2401/northstar#55]
Mod list and crash report with latest.log
[mod list.txt](https://github.com/user-attachments/files/16644664/mod.list.txt)
[1.29.txt](https://github.com/user-attachments/files/16644665/1.29.txt)
[latest.log](https://github.com/user-attachments/files/16644666/latest.log)
Please tell me why

**Comment by k0dekiller** [comment]
There seems to be an error when a Smooth Quartz block is powered / unpowered. But it's not an issue with this mod. Why did you add an issue here?

**Comment by davethemodderguy** [comment]
Oh, that's the problem? ok, isuue is over, thanks for telling me
