### ISSUE TITLE
Cant generate/render chunks on the moon

### ISSUE THREAD

**Issue by xTruesX** [lightning2401/northstar#62]
When i go to the moon a few chunks can generate and nothing else i can get 5 or 6 chunks from where my rocket lands. And nothing else. it looks like it is being generated but it does not render at all. I am using embeddium + oculus WITHOUT shaders. What can i do about this i am playing heavily modded. 

My mod list: https://pastebin.com/C6huLHpy

Example photo: https://imgur.com/a/LbwYKlk

Edit: I was trying to fix it and find out that if you are forcing chunks to generate and render it just straight up freezes your game you can walk, run, fly and do client side things but you cant eat, break blocks properly, or even go back to the overworld you need to close your game but you cant do that either. It will be stuck in the "Saving Worlds" screen. I dont think it corrupts your save but if you exit two times in the moon like i did there is no going back to the world. You are stuck there if you try to generate chunks.

**Comment by OGbubbymanYT** [comment]
this happens too on the official server

p.s. I am the owner of it

**Comment by xTruesX** [comment]
@OGbubbymanYT is there a way around this?

**Comment by OGbubbymanYT** [comment]
no not yet, I've just been giving people the interplanetary navigator to go to mars

I'm sure its being looked into though, since I did show Furiosity/(The Mod Owner) the bug

**Comment by xTruesX** [comment]
Oh ok then thanks for quick reply
