### ISSUE TITLE
размеры ракеты

### ISSUE THREAD

**Issue by seopka** [lightning2401/northstar#99]
всем привет, проявилась проблема с модом "northstar" дополнение к "create"
построил большую ракету, поставил "rocket control",пытаюсь собрать ракету но пишется что ракета слишком большая (скриншот ниже) 
![2024-12-05_08 04 36](https://github.com/user-attachments/assets/95a3f6cf-0e84-41fb-b921-eabc0ba008e5)
а именно что количество блоков ракеты превышает 2048
так же в сообщении пишется что можно изменить это значение в конфиге, вот только есть проблема...
я перерыл и папки модов,и папки игры, и настроек и нечего не нашёл.
даже код обоих модов смотрел но не смог найти 
где мне найти это значение и изменить его? очень нужно и желательно срочно, буду благодарен за решение)

**Comment by seopka** [comment]
Цитата ответ 
                                                                             ### НАШЁЛ РЕШЕНИЕ! 
Что бы увеличить максимальное значение постройки, перейдите в папку с вашими мирами->выберете ваш мир в котором вы собирайте ракету->в папке мира найдите и откройте папку "server config"  ->  "create-server.toml" и откройте последнее с помощью "notepad++"

![image](https://github.com/user-attachments/assets/0c55cb18-e1b7-4ab6-abd4-802166c55e4b)

ищем 141 строку с значением "2048" и изменяем на любое число которое хотим.

![image](https://github.com/user-attachments/assets/37b78f3e-ad5a-4fbe-98d9-220a282f2dce)

Сохраняем документ и готово !  
всё, теперь всё должно работать.

ВАЖНО! не используйте большое значение, используйте значение оптимальное для вас и вашего пк.
В случае не работы вашего мира и модов, я не несу ответственость за вас и ваши данные, спасибо!

**Comment by wolfieboy09** [comment]
I don't even know what is going on or what the issue was in the first place

**Comment by seopka** [comment]
> Я даже не знаю, что происходит или в чем изначально была проблема.

тебе нужна помощь с этой проблемой? или что? если да,то говори 
я прсото не понял твоего ответа на мой пост

у меня была проблема с ограничением постройки "в блоках" со значением "2048"
я не знал как обойти это ограничение так как настроек мод "northstar" не имеет
после чего я нашёл решение этой проблемы зайдя в конфиг мир и изменив число "2048" на "6000"

**Comment by wolfieboy09** [comment]
I can't read Russian, and Google translate is usually wrong half the time
